### ISSUE TITLE
check bài 2

### ISSUE THREAD

**Issue by HaiYenPham** [Duc-Diep/Duc-Diep.github.io#2]
https://github.com/Duc-Diep/Duc-Diep.github.io/blob/cf49cb08b73b8d245bb656223469735b42607d84/index.html#L12

bài ok rùi nhé! chơi game giỏi mà học cũng giỏi thế này <3
cố gắng phát huy nha//////

**Comment by Duc-Diep** [comment]
Oh noooooooooooooooooooo :)
