### ISSUE TITLE
check bài 3

### ISSUE THREAD

**Issue by HaiYenPham** [Duc-Diep/Duc-Diep.github.io#3]
https://github.com/Duc-Diep/Duc-Diep.github.io/blob/44288c40927c7e8ae631f5b39670619bfca3f53a/index.html#L8

bài ok rồi nhé!
phần này trên lớp có bài kiểm tra, dạy rồi mà được điểm thấp thì cứ liệu ✌️ 
thân ái và quyết thắng <3

**Comment by Duc-Diep** [comment]
Oh no :(
